name: ally_4_u_client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.2.4
  appinio_swiper: ^2.0.3
  badges: ^3.1.2
  bubble: ^1.2.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_messaging: ^14.7.4
  firebase_storage: ^11.5.1
  fl_country_code_picker: ^0.1.7+1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_inappwebview: ^5.8.0
  flutter_mapbox_autocomplete: ^2.0.0
  flutter_ringtone_player: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  geocoder2: ^1.4.0
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  in_app_purchase: ^3.1.11
  intl: ^0.18.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.1
  rflutter_alert: ^2.0.7
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  swipe_stack_null_safe: ^1.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/auth/
    - asset/Icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Regular.ttf
