name: allt_4_u_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <3.5.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
