// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
     apiKey: "AIzaSyDsUS9miwzPLSQEhNCEUsNVmJrvvI5MnZA",
    authDomain: "dating-daf3a.firebaseapp.com",
    projectId: "dating-daf3a",
    storageBucket: "dating-daf3a.appspot.com",
    messagingSenderId: "816521819994",
    appId: "1:816521819994:web:f7474d061664b0fa66e563",
    measurementId: "G-8TB14KPLKS"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKufknnmCMwVHxEaGOfKUIJ6hwjnFawUA',
    appId: '1:8224494734:android:cf80558354be7b573765df',
    messagingSenderId: '8224494734',
    projectId: 'allyforyou',
    storageBucket: 'allyforyou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkQVHHl8NvJgUqi_lmzKiRsrVo2Ar_e8E',
    appId: '1:8224494734:ios:da33b046f0f7d8623765df',
    messagingSenderId: '8224494734',
    projectId: 'allyforyou',
    storageBucket: 'allyforyou.appspot.com',
    iosClientId: '8224494734-fui9en5836hbvlueoi15qr321tni0839.apps.googleusercontent.com',
    iosBundleId: 'com.example.allt4UAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkQVHHl8NvJgUqi_lmzKiRsrVo2Ar_e8E',
    appId: '1:8224494734:ios:da33b046f0f7d8623765df',
    messagingSenderId: '8224494734',
    projectId: 'allyforyou',
    storageBucket: 'allyforyou.appspot.com',
    iosClientId: '8224494734-fui9en5836hbvlueoi15qr321tni0839.apps.googleusercontent.com',
    iosBundleId: 'com.example.allt4UAdmin',
  );
}
